[theme]
name = "gruvbox"

[theme.light]
fg_primary = "#3c3836"
fg_muted = "#7c6f64"
fg_accent = "#076678"
bg_primary = "#fbf1c7"
bg_muted = "#ebdbb2"
bg_neutral_muted = "#ebdbb266"
bg_attention_muted = "#b5761426"
bg_secondary = "#ebdbb2"
border_primary = "#d5c4a1"
border_muted = "#ebdbb2"
fg_sheen = "#3c3836"
bg_sheen = "#fbf1c7"
border_sheen = "#d5c4a1"
alert_note = "#076678"
alert_tip = "#79740e"
alert_important = "#8f3f71"
alert_warning = "#b57614"
alert_caution = "#9d0006"
alert_note_bg = "#07667833"
alert_tip_bg = "#79740e33"
alert_important_bg = "#8f3f7133"
alert_warning_bg = "#b5761433"
alert_caution_bg = "#9d000633"

[theme.light.syntax]
filepath = "./syntax/gruvbox-light.tmTheme"

[theme.dark]
fg_primary = "#ebdbb2"
fg_muted = "#a89984"
fg_accent = "#83a598"
bg_primary = "#282828"
bg_muted = "#3c3836"
bg_neutral_muted = "#3c383666"
bg_attention_muted = "#fabd2f26"
bg_secondary = "#3c3836"
border_primary = "#504945"
border_muted = "#3c3836"
fg_sheen = "#ebdbb2"
bg_sheen = "#282828"
border_sheen = "#504945"
alert_note = "#83a598"
alert_tip = "#b8bb26"
alert_important = "#d3869b"
alert_warning = "#fabd2f"
alert_caution = "#fb4934"
alert_note_bg = "#83a59833"
alert_tip_bg = "#b8bb2633"
alert_important_bg = "#d3869b33"
alert_warning_bg = "#fabd2f33"
alert_caution_bg = "#fb493433"

[theme.dark.syntax]
filepath = "./syntax/gruvbox-dark.tmTheme"
