[theme]
name = "rose-pine"

[theme.light]
fg_primary = "#575279"
fg_muted = "#9893a5"
fg_accent = "#56949f"
bg_primary = "#faf4ed"
bg_muted = "#fffaf3"
bg_neutral_muted = "#f2e9e166"
bg_attention_muted = "#ea9d3426"
bg_secondary = "#f2e9e1"
border_primary = "#dfdad9"
border_muted = "#f2e9e1"
fg_sheen = "#575279"
bg_sheen = "#faf4ed"
border_sheen = "#dfdad9"
alert_note = "#286983"
alert_tip = "#56949f"
alert_important = "#907aa9"
alert_warning = "#ea9d34"
alert_caution = "#b4637a"
alert_note_bg = "#28698333"
alert_tip_bg = "#56949f33"
alert_important_bg = "#907aa933"
alert_warning_bg = "#ea9d3433"
alert_caution_bg = "#b4637a33"

[theme.light.syntax]
filepath = "./syntax/rose-pine-dawn.tmTheme"

[theme.dark]
fg_primary = "#e0def4"
fg_muted = "#6e6a86"
fg_accent = "#9ccfd8"
bg_primary = "#191724"
bg_muted = "#1f1d2e"
bg_neutral_muted = "#26233a66"
bg_attention_muted = "#f6c17726"
bg_secondary = "#26233a"
border_primary = "#403d52"
border_muted = "#26233a"
fg_sheen = "#e0def4"
bg_sheen = "#191724"
border_sheen = "#403d52"
alert_note = "#31748f"
alert_tip = "#9ccfd8"
alert_important = "#c4a7e7"
alert_warning = "#f6c177"
alert_caution = "#eb6f92"
alert_note_bg = "#31748f33"
alert_tip_bg = "#9ccfd833"
alert_important_bg = "#c4a7e733"
alert_warning_bg = "#f6c17733"
alert_caution_bg = "#eb6f9233"

[theme.dark.syntax]
filepath = "./syntax/rose-pine.tmTheme"
