[theme]
name = "solarized"

[theme.light]
fg_primary = "#657b83"
fg_muted = "#93a1a1"
fg_accent = "#268bd2"
bg_primary = "#fdf6e3"
bg_muted = "#eee8d5"
bg_neutral_muted = "#eee8d566"
bg_attention_muted = "#b5890026"
bg_secondary = "#eee8d5"
border_primary = "#93a1a1"
border_muted = "#eee8d5"
fg_birta = "#586e75"
bg_birta = "#fdf6e3"
border_birta = "#eee8d5"
alert_note = "#268bd2"
alert_tip = "#859900"
alert_important = "#6c71c4"
alert_warning = "#b58900"
alert_caution = "#dc322f"
alert_note_bg = "#268bd233"
alert_tip_bg = "#85990033"
alert_important_bg = "#6c71c433"
alert_warning_bg = "#b5890033"
alert_caution_bg = "#dc322f33"

[theme.light.syntax]
filepath = "./syntax/solarized-light.tmTheme"

[theme.dark]
fg_primary = "#839496"
fg_muted = "#586e75"
fg_accent = "#268bd2"
bg_primary = "#002b36"
bg_muted = "#073642"
bg_neutral_muted = "#07364266"
bg_attention_muted = "#b5890026"
bg_secondary = "#073642"
border_primary = "#586e75"
border_muted = "#073642"
fg_birta = "#93a1a1"
bg_birta = "#002b36"
border_birta = "#073642"
alert_note = "#268bd2"
alert_tip = "#859900"
alert_important = "#6c71c4"
alert_warning = "#b58900"
alert_caution = "#dc322f"
alert_note_bg = "#268bd233"
alert_tip_bg = "#85990033"
alert_important_bg = "#6c71c433"
alert_warning_bg = "#b5890033"
alert_caution_bg = "#dc322f33"

[theme.dark.syntax]
filepath = "./syntax/solarized-dark.tmTheme"
