[theme]
name = "synthwave-84"

[theme.dark]
fg_primary = "#ffffff"
fg_muted = "#848bbd"
fg_accent = "#ff7edb"
bg_primary = "#262335"
bg_muted = "#241b2f"
bg_neutral_muted = "#241b2f66"
bg_attention_muted = "#f3e70f26"
bg_secondary = "#171520"
border_primary = "#34294f"
border_muted = "#241b2f"
fg_birta = "#ffffff"
bg_birta = "#262335"
border_birta = "#34294f"
alert_note = "#03edf9"
alert_tip = "#72f1b8"
alert_important = "#ff7edb"
alert_warning = "#fede5d"
alert_caution = "#fe4450"
alert_note_bg = "#03edf933"
alert_tip_bg = "#72f1b833"
alert_important_bg = "#ff7edb33"
alert_warning_bg = "#fede5d33"
alert_caution_bg = "#fe445033"

[theme.dark.syntax]
filepath = "./syntax/synthwave-84.tmTheme"
